[project]
name = "python-learn-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbutils>=3.1.2",
    "django>=6.0",
    "flask>=3.1.2",
    "numpy>=2.4.0",
    "pymysql>=1.1.2",
    "redis>=7.1.0",
]
