[project]
name = "intel-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-search-results>=2.4.2",
    "load-dotenv>=0.1.0",
    "openai>=2.8.1",
]
